name: push nix cache

on:
  push:
    branches:
      - master

jobs:
  cache:
    runs-on: native-x86_64-linux
    steps:
      - uses: actions/checkout@v4
      - run: nix run .#cache -L --accept-flake-config
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
