name: push nix cache
"on":
  push:
    branches:
      - master
jobs:
  cache:
    runs-on: [native-x86_64-linux, bigger-parallel]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - run: nix run .#cache -L --accept-flake-config
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
