name: push nix cache
"on":
  push:
    branches:
      - master
jobs:
  cache:
    runs-on: native-x86_64-linux
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: nix run .#cache -L --accept-flake-config
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
